01-svelte/06-bindings/01-text-inputs
Svelte-Korea/learn.svelte.kr pull request #112
Opened 2024-05-29 03:54 UTC by HarunaMahjong

01-svelte/06-bindings/01-text-inputs

- [번역 풀 리퀘스트Translation PR Template](?expand=1&template=translation_pr_template.md)

2024-06-01 23:29 UTC, Jueun-Park approved these changes
LGTM

2024-08-30 09:29 UTC, dodok8 requested changes

2024-08-30 09:29 UTC, dodok8 commented on content/tutorial/01-svelte/06-bindings/01-text-inputs/README.md
> +일반적으로 스벨트에서 데이터 흐름은 _상향식_ 입니다. 부모 컴포넌트는 자식 컴포넌트에 프롭(props)을 설정할 수 있고, 컴포넌트는 요소에 속성을 설정할 수 있지만, 반대 방향은 불가능합니다.
```suggestion
일반적으로 스벨트에서 데이터 흐름은 _하향식_ 입니다. 부모 컴포넌트는 자식 컴포넌트에 프롭(props)을 설정할 수 있고, 컴포넌트는 요소에 속성을 설정할 수 있지만, 반대 방향은 불가능합니다.
```

정반대로 되어 있습니다.

2024-08-30 09:29 UTC, dodok8 commented on content/tutorial/01-svelte/06-bindings/01-text-inputs/README.md
> +이는 `name`의 값이 변경되면 입력 값이 업데이트될 뿐만 아니라, 입력 값이 변경되면 `name`도 업데이트됨을 의미합니다.
```suggestion
이렇게 하면 `name`의 값의 변화에 따라 입력 값이 변경될 뿐만 아니라, 입력 값이 변경되는 경우에도 `name`도 업데이트되게 됩니다.
```

2025-12-29 05:52 UTC, closed without merging