Transalte 01-svelte/01-introduction/04-styling and 05-nested-compoents
Svelte-Korea/learn.svelte.kr pull request #13
Opened 2024-02-12 04:37 UTC by cog25

2024-02-18 12:50 UTC, Jueun-Park requested changes
의견 드립니다 ㅎㅎ

2024-02-18 12:50 UTC, Jueun-Park commented on content/tutorial/01-svelte/01-introduction/04-styling/README.md
> +중요한 것은, 방금 작성한 규칙들은 _컴포넌트 범위에서만 적용_ 됩니다. 다읍 단계에서 보겠지만, 이는 실수로 앱의 다른 부분에서 `<p>` 요소의 스타일을 변경할 일이 없음을 의미합니다.
다읍 단계 -> 다음 단계

2024-02-18 12:50 UTC, Jueun-Park commented on content/tutorial/01-svelte/01-introduction/05-nested-components/README.md
> +... 그리고 `<Nested />` 를 추가합니다.
어조를 맞추어서 `추가하면...`으로 번역하는 건 어떨까요? 다른 의견도 환영합니다.

2024-02-19 14:18 UTC, D0ri123 commented on content/tutorial/01-svelte/01-introduction/05-nested-components/README.md
> +... 그리고 `<Nested />` 를 추가합니다.
뒤에 '그리고~'라고 시작을 해서 `추가해주세요.`로 끝내는 것도 깔끔해 보여요!

2024-02-19 14:18 UTC, D0ri123 commented on content/tutorial/01-svelte/01-introduction/05-nested-components/README.md
> +`Nested.svelte`가 `<p>` 요소를 포함하지만, `App.svelte`의 스타일이 적용되지 않음을 유의하세요.
사람마다 다르게 느낄수도 있는데 `적용되지 않음을 유의하세요` 라는 어조가 자연스럽지 않다고 느껴집니다.
이대로 해도 의미 전달은 잘 될 수 있을 것 같은데요. `~를 포함하지만, ~의 스타일이 적용되지는 않습니다.` 
이렇게 적는 것도 하나의 방법이 될 수 있을 것 같아요! 이 부분에 대해서 다른 분들의 의견도 들어보고 싶습니다!

2024-02-19 14:27 UTC, cog25 commented on content/tutorial/01-svelte/01-introduction/05-nested-components/README.md
> +`Nested.svelte`가 `<p>` 요소를 포함하지만, `App.svelte`의 스타일이 적용되지 않음을 유의하세요.
너무 직역을 해버렸네요... 다시 원문이랑 일본어 번역을 참고해보니 직접 playground를 보고 확인해보길 의도한 것 같아, `~ 스타일이 적용되지 않음을 확인해 보세요` 정도가 어떨까요?

2024-02-19 14:30 UTC, cog25 commented on content/tutorial/01-svelte/01-introduction/05-nested-components/README.md
> +... 그리고 `<Nested />` 를 추가합니다.
원문에서 문장을 종결하는 느낌으로 사용된 것 같아, 일단은 `추가해 주세요.`로 하겠습니다!

2024-02-24 07:11 UTC, Jueun-Park approved these changes
lgtm

2024-02-24 07:19 UTC, merged