Translate 02-advanced-svelte/01-motion
Svelte-Korea/learn.svelte.kr pull request #18
Opened 2024-02-12 05:55 UTC by dodok8

Close #17

2024-02-28 13:32 UTC, Jueun-Park requested changes
확인 부탁드립니다~

2024-02-28 13:32 UTC, Jueun-Park commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +- `interpolate` — 커스텀 `(from, to) => t => value` 함수로 임의의 값 사이를 보간하는 데 사용합니다. 기본적으로 Svelte 는 숫자, 날짜, 그리고 동형으로 생긴 배열과 오브젝트 값 사이를 보간할 것입니다  숫자, 날짜, 아니면 다른 유효한 배열과 오브젝트만 가지고 있는 한 말이죠. 만약 당신이, 예를 들어, 색깔 문
`커스텀` -> `사용자 정의` 로 수정하는 방안
`만약 당신이` 등의 주어를 생략하여 자연스러운 문장을 만드는 방안

2024-02-28 13:32 UTC, Jueun-Park commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +이 옵션들을 `progress.set` 와 `progress.update`에 2번째 파라미터값으로 넣어줄 수 있습니다. 그 경우 기본값을 덮어 쓰게 됩니다. `set` 과 `update` 메쏘드는 프로미스(promise)를 반환하고, 이 프로미스는 트윈이 완료되는 시점에 resolve 됩니다.
메쏘드 -> 메서드
이렇게 번역했던 것 같은데 레퍼런스를 못 찾았네요... 혹시 누가 보시면 코멘트 부탁드려요

2024-03-02 06:49 UTC, D0ri123 commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +이 옵션들을 `progress.set` 와 `progress.update`에 2번째 파라미터값으로 넣어줄 수 있습니다. 그 경우 기본값을 덮어 쓰게 됩니다. `set` 과 `update` 메쏘드는 프로미스(promise)를 반환하고, 이 프로미스는 트윈이 완료되는 시점에 resolve 됩니다.
연관은 없지만,, [마이크로 소프트사의 C# 프로그래밍 가이드](https://learn.microsoft.com/ko-kr/dotnet/csharp/programming-guide/classes-and-structs/methods) 찾아보면 메서드라고 하네요!
근데 Ncloud 가이드에서는 메소드라고 하고, okky 커뮤니티에서는 메쏘드라고 하시는 분들도 계시고 엄청 다양해서요..

[위키백과](https://ko.wikipedia.org/wiki/%EB%A9%94%EC%84%9C%EB%93%9C_(%EC%BB%B4%ED%93%A8%ED%84%B0_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D))에서는 메서드라고 표기하고 있는데 이걸 따라가는건 어떨까요?

2024-03-03 06:51 UTC, dodok8 commented on content/tutorial/02-advanced-svelte/01-motion/01-tweens/README.md
> +이 옵션들을 `progress.set` 와 `progress.update`에 2번째 파라미터값으로 넣어줄 수 있습니다. 그 경우 기본값을 덮어 쓰게 됩니다. `set` 과 `update` 메쏘드는 프로미스(promise)를 반환하고, 이 프로미스는 트윈이 완료되는 시점에 resolve 됩니다.
말씀하신대로 수정하겠습니다.

2024-03-03 07:09 UTC, Jueun-Park approved these changes
LGTM

2024-03-03 07:10 UTC, merged