Translate 04-advanced-sveltekit/03-link-options
Svelte-Korea/learn.svelte.kr pull request #34
Opened 2024-03-05 13:40 UTC by suhyeoonn

Close #30

2024-03-09 10:44 UTC, Jueun-Park requested changes
기여해주셔서 감사합니다! 코멘트 확인 부탁드려요~

2024-03-09 10:44 UTC, Jueun-Park commented on content/tutorial/04-advanced-sveltekit/03-link-options/01-preload/README.md
> +`data-sveltekit-preload-data`를 사용하면 페이지의 모든 내용이 로드되지만, 때로는 데이터 로드를 원치 않을 수도 있습니다. `data-sveltekit-preload-code` 속성을 사용하면 데이터를 로드하지 않고 특정 경로에 필요한 JavaScript만 미리 로드할 수 있습니다. 이 속성은 다음 값을 가집니다.
> Using `data-sveltekit-preload-data` may sometimes result in false positives - i.e. loading data in anticipation of a navigation that doesn't then happen — which might be undesirable.

이 부분에 생략이 일어나서 매끄럽게 번역되긴 했는데, `i.e. loading data in anticipation of a navigation that doesn't then happen` 부분의 내용이 추가되면 더 자세할 것 같다는 생각이 들어요 🤔 

> `data-sveltekit-preload-data`를 사용하면 페이지의 모든 내용이 로드되지만, 경로 탐색이 발생하지 않을 것으로 예상하여 데이터를 로드하는 경우처럼 때로는 데이터 로드를 원치 않을 수도 있습니다.

처럼 작성할 수도 있을 것 같고, 이것이 너무 장황한 것 같다면

> `data-sveltekit-preload-data`를 사용하면 페이지의 모든 내용이 로드되지만, 때로는 데이터 로드를 원치 않을 수도 있습니다(예를 들어, 경로 탐색이 발생하지 않을 것으로 예상하여 데이터를 로드하는 경우).

정도로 괄호를 사용해 번역하는 건 어떨까요?

2024-03-09 10:44 UTC, Jueun-Park commented on content/tutorial/04-advanced-sveltekit/03-link-options/01-preload/README.md
> +- `"hover"` (기본값) 위와 동일
(질문) `viewport` 와 같다는 뜻이 아니라 위쪽 `hover`에 서술된 것과 같다는 뜻이지요 ..?!

2024-03-09 10:44 UTC, Jueun-Park commented on content/tutorial/04-advanced-sveltekit/03-link-options/01-preload/README.md
> +또한 프로그래밍적으로도 `$app/navigation`에서 가져온 `preloadCode` 와 `preloadData`를 사용하여 사전 로딩을 할 수도 있습니다.
아래 코드의 주석도 번역이 필요할 것 같아요~ (문장으로 된 부분만?..)

2024-03-09 10:44 UTC, Jueun-Park commented on content/tutorial/04-advanced-sveltekit/03-link-options/02-reload/README.md
> +사용 가능한 링크 옵션과 해당 값에 대한 자세한 내용은 [link options 문서](https://kit.svelte.dev/docs/link-options)를 참조하세요.
(논의 포인트) 번역 시 svelte.dev 등으로 가는 링크를 kr 버전으로 바꾸어야 하는지 (#32 에서 논의)

2024-03-09 18:26 UTC, suhyeoonn commented on content/tutorial/04-advanced-sveltekit/03-link-options/01-preload/README.md
> +- `"hover"` (기본값) 위와 동일
네~! 위쪽 `hover`와 같다는 뜻인데 헷갈릴 것 같아 `위와 동일` 대신, 위에서 서술한 내용들 동일하게 기재하였습니다!

2024-03-09 18:35 UTC, suhyeoonn commented on content/tutorial/04-advanced-sveltekit/03-link-options/02-reload/README.md
> +사용 가능한 링크 옵션과 해당 값에 대한 자세한 내용은 [link options 문서](https://kit.svelte.dev/docs/link-options)를 참조하세요.
아직 논의된 부분은 없는 것 같은데 우선 현재 링크 그대로 두면 될까요...??

2024-03-11 10:40 UTC, Jueun-Park commented on content/tutorial/04-advanced-sveltekit/03-link-options/02-reload/README.md
> +사용 가능한 링크 옵션과 해당 값에 대한 자세한 내용은 [link options 문서](https://kit.svelte.dev/docs/link-options)를 참조하세요.
네넵~!

2024-03-11 10:41 UTC, Jueun-Park approved these changes
LGTM

2024-03-14 09:43 UTC, dodok8 commented
LGTM

머지하겠습니다.

2024-03-14 09:43 UTC, merged