Translate 03-sveltekit/07-api-routes
Svelte-Korea/learn.svelte.kr pull request #39
Opened 2024-03-26 09:34 UTC by dodok8

Close #37

2024-03-27 13:36 UTC, Jueun-Park requested changes
번역 기여 감사합니다! 확인 부탁드려요 ㅎㅎ~

2024-03-27 13:36 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/07-api-routes/02-post-handlers/README.md
> +`<input>` 안에 있는 '할일 추가' `keydown` 이벤트 핸들러에서, 서버로 데이터를 포스트 해봅시다.
여기 뭔가 조금 어색한데 의도한 뜻이 맞나요?

제안:
> 'add a todo' `<input>` 안의 `keydown` 이벤트 핸들러에서, 서버로 데이터를 POST 해 봅시다.

2024-03-27 13:36 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/07-api-routes/02-post-handlers/README.md
> +이제 JSON을 `/todo` API 라우트로 포스트 해봅시다. 쿠키에 있는 `userid` 값을 보내고, 응답 안에 새 할 일의 `id` 를 받아봅시다.
제안:
> 응답 안에 있는 새 할 일의 `id` 를 받아봅시다.

2024-03-27 13:36 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/07-api-routes/02-post-handlers/README.md
> +`load` 함수와 폼 액션과 마찬가지로, `request`는 표준 `[리퀘스트Request](https://developer.mozilla.org/en-US/docs/Web/API/Request)` 객체입니다. `await request.json()`는 이벤트 핸들러로 포스트 된 데이터를 반환합니다.
제안:
>`load` 함수 및 폼 액션과 마찬가지로, `request`는 표준 `[리퀘스트Request](https://developer.mozilla.org/en-US/docs/Web/API/Request)` 객체입니다. 즉, `await request.json()`는 이벤트 핸들러로 포스트 된 데이터를 반환합니다.

2024-03-27 13:36 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/07-api-routes/02-post-handlers/README.md
> +> 페이지를 다시 로드해도 같은 결과를 얻을 수 있도록 `data`를 변경해야 합니다.
확실치 않은데 여기 뭔가 어색한 기분이에요 혹시 의견 있으신가요 ..?

기계번역 (deepl) 결과:
> 페이지를 다시 로드해도 동일한 결과를 얻을 수 있는 방식으로만 '데이터'를 변경해야 합니다.

제안:
> `data`는 페이지를 다시 로드해도 같은 결과를 얻을 수 있는 방식으로 변경해야 합니다.

2024-03-27 13:36 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/07-api-routes/03-other-handlers/README.md
> +브라우저에 실제 데이터를 반환하지 않으니, 비어있는 [리스폰스(response](https://developer.mozilla.org/en-US/docs/Web/API/Response)를 [204 No Content](https://http.dog/204) 상태코드로 반환하도록 합시다.
제안:
`브라우저에 실제 데이터를 반환할 필요가 없으니, 비어있는 [리스폰스(response](https://developer.mozilla.org/en-US/docs/Web/API/Response)를 [204 No Content](https://http.dog/204) 상태코드와 함께 반환하도록 합시다.`

2024-03-27 13:36 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/07-api-routes/03-other-handlers/README.md
> +다른 HTTP 메쏘드에 대해서도 비슷하게 핸들러를 만들 수 있습니다. `src/lib/server/database.js`에 있는 `toggleTodo` 와 `deleteTodo` 를 이용해 할 일을 껐다 켜도록 `PUT` 과 `DELETE` 핸들러를 `src/routes/todo/[id]/+server.js`에 만들어, `/todo/[id]` 라우트를 추
메쏘드 -> 메서드 어떨까요?
그리고 사소하지만 문장 순서를 좀 바꿔서 다듬어보면 읽기 쉬우려나요...

제안:
> 다른 HTTP 메서드에 대해서도 비슷하게 핸들러를 만들 수 있습니다. `src/lib/server/database.js`에 있는 `toggleTodo` 와 `deleteTodo` 를 이용해 할 일을 껐다 키고 삭제할 수 있도록 `src/routes/todo/[id]/+server.js`에 `PUT` 과 `DELETE` 핸들러를 만들어, `/todo/[id]` 라우트를 추가합시다.

2024-03-28 09:35 UTC, dodok8 commented
@Jueun-Park 님 의견대로 수정하였습니다.

2024-04-10 08:36 UTC, Jueun-Park approved these changes
LGTM

2024-04-10 08:40 UTC, merged