Translate 06-Forms/01-the-form-element
Svelte-Korea/learn.svelte.kr pull request #40
Opened 2024-03-26 15:16 UTC by D0ri123

2024-03-29 09:53 UTC, dodok8 requested changes
번역과 표기에 관한 의견 적었습니다.

2024-03-29 09:53 UTC, dodok8 commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +todo 앱을 만들어 봅시다. 이미 src/lib/server/database.js에 메모리 내 데이터베이스가 설정되어 있고, `src/routes/+page.server.js`의 load 함수는 [`cookies`](https://kit.svelte.dev/docs/load#cookies) API를 사용하여 각 사용자마다 할 일 목록을 가질 수 있도록
`src/lib/server/database.js` 에 백틱 빼먹으셨습니다.

2024-03-29 09:53 UTC, dodok8 commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +[데이터 로딩](page-data) 장에서는 서버에서 브라우저로 데이터를 가져오는 방법을 살펴보았습니다. 어떤 때에는 데이터를 반대 방향으로 보내야 할 필요가 있으며, 이를 위해 웹 플랫폼에서 데이터를 전송하는 방법으로 `<form>`이 사용됩니다.
다른 부분에서는 장 대신에 챕터라는 단어를 사용햇습니다. 그리고 말이 너무 딱딱한 것 같아서 아래와 같은 번역을 제안합니다.

> [데이터 로딩](page-data) 챕터에서는 서버에서 브라우저로 데이터를 가져오는 방법을 살펴보았습니다. 데이터를 반대 방향으로 보내는 경우도 있는데, 이 때 웹 플랫폼에서 데이터를 전송하는 방법으로 `<form>`을 사용합니다.

2024-03-29 09:53 UTC, dodok8 commented on content/tutorial/03-sveltekit/06-forms/meta.json
> +	"title": "폼(Forms)"
#31 에서 타이틀에 원문 병기 안하기로 했으므로, 괄호 안은 필요없습니다.

2024-03-29 09:53 UTC, dodok8 commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +`request`는 표준 [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) 객체입니다. `await request.formData()`는 [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) 인스턴스를 반환합니
`;`은 앞의 문장에 추가적인 내용을 덧붙일 때 사용하는 문장 부호이므로, 접속사를 추가하는 것이 자연스러울 것 같습니다.

> `request`는 표준 [리퀘스트(Request)](https://developer.mozilla.org/en-US/docs/Web/API/Request) 객체입니다. 따라서 `await request.formData()`는 [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) 인스턴스를 반환합니다.

2024-03-29 09:53 UTC, dodok8 commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +`<input>`에 무언가를 입력하고 Enter를 누르면, `method="POST"` 속성으로 브라우저가 현재 페이지로 POST 요청을 보냅니다. 그러나 POST 요청을 처리할 서버 측 *액션*을 만들지 않았기 때문에 오류가 발생합니다. 이제 그것을 해결해 봅시다.
Enter 를 어떻게 표기할지 논의해 봐야할 것 같습니다. 저는 엔터 그대로 음차해서 적는게 자연스럽다 생각합니다.

그와 별개로 번역을 아래와 같이 수정하면 더 좋을 것 같습니다.

> `<input>`에 무언가를 입력하고 Enter를 누르면, `method="POST"` 속성에따라 브라우저는 현재 페이지로 POST 요청을 보냅니다. 그러나 POST 요청을 처리할 서버 측 *액션*을 만들지 않았기 때문에 오류가 발생합니다. 이제 만들어 봅시다.

2024-04-15 12:51 UTC, D0ri123 commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +`<input>`에 무언가를 입력하고 Enter를 누르면, `method="POST"` 속성으로 브라우저가 현재 페이지로 POST 요청을 보냅니다. 그러나 POST 요청을 처리할 서버 측 *액션*을 만들지 않았기 때문에 오류가 발생합니다. 이제 그것을 해결해 봅시다.
저도 엔터는 그대로 음차해서 적는게 더 자연스러워 보여서 반영해두겠습니다. 가이드의 `번역팁` 목차에 넣어두는게 어떨까요?

2024-04-17 13:28 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +`<input>`에 무언가를 입력하고 Enter를 누르면, `method="POST"` 속성으로 브라우저가 현재 페이지로 POST 요청을 보냅니다. 그러나 POST 요청을 처리할 서버 측 *액션*을 만들지 않았기 때문에 오류가 발생합니다. 이제 그것을 해결해 봅시다.
동의합니다~ contributind.md 에는 이렇게 반영해 보았습니다 https://github.com/Svelte-Korea/learn.svelte.kr/pull/36/commits/800dc661751600c790a6139c309af1c8d3a36e71

2024-04-22 05:37 UTC, dodok8 approved these changes
LGMT

2024-05-06 05:53 UTC, merged