Translate/08 stores
Svelte-Korea/learn.svelte.kr pull request #42
Opened 2024-03-29 10:25 UTC by dodok8

Close #41

2024-03-29 11:00 UTC, dodok8 commented
페이지 타이틀에 쓰인 스토어 명을 번역을 해야할지 말아야할지 고민입니다. 사실 안하는 게 맞는 것 같기도 한데 일단 음차한 상태입니다.

2024-04-10 09:13 UTC, Jueun-Park requested changes

2024-04-10 09:13 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +스벨트킷은 3가지 기본 스토어를 `$app.stores` 모듈을 통해 제공합니다. `page`, `navigating` 그리고 `updated`입니다. 가장 자주 사용하게 될 스토어는 [`page`](https://kit.svelte.dev/docs/types#public-types-page)입니다. 현재 페이지에 관한 정보를 제공하는 스토어입니다.
`$app/stores` 랑 `$app.stores`는 같은 건가요?

2024-04-10 09:13 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +스벨트킷은 3가지 기본 스토어를 `$app.stores` 모듈을 통해 제공합니다. `page`, `navigating` 그리고 `updated`입니다. 가장 자주 사용하게 될 스토어는 [`page`](https://kit.svelte.dev/docs/types#public-types-page)입니다. 현재 페이지에 관한 정보를 제공하는 스토어입니다.
제안:
> 3가지 기본 스토어는 `page`, `navigating`, `updated`입니다. 가장 자주 사용하게 될 스토어는 [`page`](https://kit.svelte.dev/docs/types#public-types-page)입니다. 이는 현재 페이지에 관한 정보를 제공하는 스토어입니다.

2024-04-10 09:13 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/08-stores/meta.json
> +	"title": "스토어"
이 쪽에서 음차했으므로 문서에서 처음 용어가 나오는 부분에 병기할까요? (파트 1의 writable stores 에서 처음 나오나요? 혹은 이 파트 3의 처음인 page store에서 병기할까요?)

2024-04-10 09:33 UTC, dodok8 commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +스벨트킷은 3가지 기본 스토어를 `$app.stores` 모듈을 통해 제공합니다. `page`, `navigating` 그리고 `updated`입니다. 가장 자주 사용하게 될 스토어는 [`page`](https://kit.svelte.dev/docs/types#public-types-page)입니다. 현재 페이지에 관한 정보를 제공하는 스토어입니다.
> `$app/stores` 랑 `$app.stores`는 같은 건가요?

이 부분은 오타입니다. 말씀해주신 내용 기반으로 번역 수정했습니다.

2024-04-10 09:42 UTC, dodok8 commented on content/tutorial/03-sveltekit/08-stores/meta.json
> +	"title": "스토어"
https://github.com/Svelte-Korea/learn.svelte.kr/pull/31#issuecomment-1975071526

이 논의 생각하면 굳이 병기 안해도 될 것 같습니다.

2024-04-15 13:20 UTC, D0ri123 commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +스벨트킷은 `$app/stores` 모듈을 통해 기본 스토어를 제공합니다. 3가지 기본 스토어는 `page`, `navigating`, `updated`입니다. 가장 자주 사용하게 될 스토어는 page입니다. 이는 현재 페이지에 관한 정보를 제공하는 스토어입니다.
영어 상으로는 readonly가 읽기 전용이지 않을까 싶어서요. 기본이라고 지칭하신 이유가 있으실까요?

2024-04-15 13:20 UTC, D0ri123 commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +* `error` — 현재 페이지에 에러가 있는 경우에 에러 정보([나중에](error-basics) [배올 내용에서](handleerror) 더 자세히 다루겠습니다.)
'배올' 오타 있습니다.

2024-04-15 13:20 UTC, D0ri123 commented on content/tutorial/03-sveltekit/08-stores/02-navigating-store/README.md
> +`navigating` 스토어는 현재 네비게이션 정보를 담고 있습니다. 링크를 클릭하거나, 앞/뒤로 이동하거나, 프로그램적인 `goto`문 과 같이 네비게이션이 지삭되는 경우에, `navigation`에는 다음과 같은 속성을 가지는 오브젝트가 됩니다.
오타/조사 수정, 표현을 좀 다듬어봤습니다. 아래처럼 변경하는건 어떨까요? 프로그램적인 goto라는 표현이 어색하다고 느껴져 표현을 수정해봤습니다. 
> 링크 클릭, 앞뒤로 이동 또는 자동으로 이동하여 네비게이션이 시작될 때, `navigation`은 다음과 같은 속성을 가지는 오브젝트가 됩니다.

2024-04-16 09:05 UTC, dodok8 commented on content/tutorial/03-sveltekit/08-stores/01-page-store/README.md
> +스벨트킷은 `$app/stores` 모듈을 통해 기본 스토어를 제공합니다. 3가지 기본 스토어는 `page`, `navigating`, `updated`입니다. 가장 자주 사용하게 될 스토어는 page입니다. 이는 현재 페이지에 관한 정보를 제공하는 스토어입니다.
수정 했습니다.

2024-04-16 09:08 UTC, dodok8 commented on content/tutorial/03-sveltekit/08-stores/02-navigating-store/README.md
> +`navigating` 스토어는 현재 네비게이션 정보를 담고 있습니다. 링크를 클릭하거나, 앞/뒤로 이동하거나, 프로그램적인 `goto`문 과 같이 네비게이션이 지삭되는 경우에, `navigation`에는 다음과 같은 속성을 가지는 오브젝트가 됩니다.
백틱을 넣은게 계획적(programmatic)으로 일어나는 `goto`를 강조하려는 의미 같아서 `goto`를 살렸습니다. 프로그램적이라는 말이 어색하다는데는 동의 합니다. `goto`에 대해서만 좀 더 의논이 필요할 것 같습니다.

2024-05-06 05:48 UTC, dodok8 commented on content/tutorial/03-sveltekit/08-stores/02-navigating-store/README.md
> +`navigating` 스토어는 현재 네비게이션 정보를 담고 있습니다. 링크를 클릭하거나, 앞/뒤로 이동하거나, 프로그램적인 `goto`문 과 같이 네비게이션이 지삭되는 경우에, `navigation`에는 다음과 같은 속성을 가지는 오브젝트가 됩니다.
이 부분에 대한 의논 이번 주 내에 없으면 토요일에 번역 수정해서 올리겠습니다.

2024-05-06 05:56 UTC, Jueun-Park approved these changes
LGTM

2024-05-14 09:05 UTC, merged