Translate 03-sveltekit/09-errors-and-redirects
Svelte-Korea/learn.svelte.kr pull request #52
Opened 2024-05-15 07:01 UTC by dodok8

### 확인 사항

- [x] PR 제목에 번역한 파일의 폴더명을 작성해주세요. (폴더명이 너무 많다면 분리해서 PR을 올려 주세요)
- [x] 번역 후 로컬에서 렌더링이 잘 되는지 확인했나요? (로컬 실행 방법 참고: [README.md](/README.md))
- [x] 관련된 제목을 모두 번역했나요? (`README.md` 및 `meta.json`)

### 번역할 때 신경쓰거나 고민한 부분

- 3번째 항목의 `fallback` 부분이 고민입니다. 일단 음차하긴 했으나 더 좋음 번역이 있으면 수정해야합니다.

Close #51

2024-05-15 08:58 UTC, Jueun-Park requested changes
리뷰했습니다~

2024-05-15 08:58 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +다른 모든 에러는 예상치 못한 에러로 취급됩니다. `sr/routes/unexpected/+page.server.js` 에 예시가 있습니다.
sr -> src
오타인 것 같습니다

2024-05-15 08:58 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +> 나중 챕터에서 `handleError` 훅을 이용한 커스텀 에러 처리법을 배워보겠습니다.
훅 (hook) 병기 필요할까요?

2024-05-15 08:58 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +> 나중 챕터에서 `handleError` 훅을 이용한 커스텀 에러 처리법을 배워보겠습니다.
이미 잘 알려진 단어면 필요 없을 것 같기도 하고요...

2024-05-15 08:58 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/09-errors-and-redirects/03-fallback-errors/README.md
> +title: 에러 폴백
이 부분은 제목이라 음차하고 번역 없는 것이 자연스러워 보여서 이렇게 진행하는 것 동의합니다

2024-05-15 08:58 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/09-errors-and-redirects/04-redirects/README.md
> +- `303` — 폼 액션에서 성공적인 제출 다음에 사용.
끝에 온점이 없는 것이 일관성 있고 깔끔할 것 같아요

2024-05-15 08:58 UTC, Jueun-Park commented on content/tutorial/03-sveltekit/09-errors-and-redirects/03-fallback-errors/README.md
> +루트 레이아웃 데이터를 불러오는 과정에 발생한 에러와 에러 페이지를 불러오는 중에 에러가 발생하는 것처럼 진짜 심각한 일이 일어난다면, 스벨트킷은 정적인 에러 페이지를 띄워 대응(fall back)합니다.
여기서는 `대응(폴백, fall back)` 이런 식으로  병기하는 건 어떨까요?

2024-05-16 09:55 UTC, dodok8 commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +> 나중 챕터에서 `handleError` 훅을 이용한 커스텀 에러 처리법을 배워보겠습니다.
다른 분들 의견도 들어봐야할 것 같습니다.

2024-05-21 09:46 UTC, dodok8 commented on content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/README.md
> +> 나중 챕터에서 `handleError` 훅을 이용한 커스텀 에러 처리법을 배워보겠습니다.
일단 가이드라인에서는 처음 쓰이는 부분이나 강조에 대해서만 표기하라 했는데, 두 경우에 다 해당하지 않고, 기존에도 이미 `훅`으로만 표기한 부분들이 있어서 표기할 필요가 없을 것 같습니다.

2024-05-30 09:20 UTC, Jueun-Park approved these changes

2024-05-30 09:20 UTC, merged