01-svelte/03-props/02-default-values
Svelte-Korea/learn.svelte.kr pull request #85
Opened 2024-05-29 03:00 UTC by HarunaMahjong

01-svelte/03-props/02-default-values README.md 번역했습니다.

- [번역 풀 리퀘스트Translation PR Template](?expand=1&template=translation_pr_template.md)

2024-05-30 09:13 UTC, Jueun-Park requested changes
확인 부탁드려요~

2024-05-30 09:13 UTC, Jueun-Park commented on content/tutorial/01-svelte/03-props/02-default-values/README.md
> +프롭의 기본값을 쉽게 지정할 수 있습니다. `Nested.svelte`를 봐 봅시다.
`봐 봅시다` -> `살펴봅시다` 정도가 자연스러울 것 같습니다

2024-05-30 21:44 UTC, HarunaMahjong commented on content/tutorial/01-svelte/03-props/02-default-values/README.md
> +프롭의 기본값을 쉽게 지정할 수 있습니다. `Nested.svelte`를 봐 봅시다.
말씀해주신 의견 반영해 수정했습니다!

2024-06-01 08:01 UTC, Jueun-Park approved these changes
LGTM

2024-08-29 09:19 UTC, merged